// Code generated by Webpb compiler, do not edit.
// https://github.com/linqu-tech/webpb
package test;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import include.Enum;
import include.Message;
import include2.Message.Nested;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import java.util.Map;
import lombok.ToString;
import tech.linqu.webpb.runtime.Any;
import tech.linqu.webpb.runtime.WebpbMessage;
import tech.linqu.webpb.runtime.WebpbMeta;
import tech.linqu.webpb.runtime.common.InQuery;
import tech.linqu.webpb.tests.Const;
import test.Test.NestedTest;
import test.Test.Test17;

@JsonIgnoreProperties(ignoreUnknown = true)
@ToString
@JsonInclude(Include.NON_NULL)
public class Test implements WebpbMessage {

    public static final String WEBPB_METHOD = "GET";

    public static final String WEBPB_CONTEXT = "/test";

    public static final String WEBPB_PATH = "/test/{test1}";

    public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

    @Override
    public WebpbMeta webpbMeta() {
        return WEBPB_META;
    }

    @InQuery
    private Integer test1;

    @NotNull
    private Message test2;

    private Enum test3;

    private Test4 test4;

    private Map<Long, Integer> test5;

    private Map<Integer, Message> tests6;

    private Any test7;

    private NestedTest test8;

    private Long test10;

    private List<Message> test11;

    private Message.Nested test12;

    private List<include2.Message> test13;

    private Nested test14;

    @Pattern(regexp = Const.REGEX)
    private String test15;

    private byte[] test16;

    private Test17 test17;

    private Integer test18;

    private String test19;

    public Test() {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class NestedTest implements WebpbMessage {

        public static final String WEBPB_METHOD = "GET";

        public static final String WEBPB_CONTEXT = "/test";

        public static final String WEBPB_PATH = "/test/nested/{test1}";

        public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

        @Override
        public WebpbMeta webpbMeta() {
            return WEBPB_META;
        }

        private Integer test1;

        public NestedTest() {
        }

        public NestedTest(Integer test1) {
            this.test1 = test1;
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Test17 implements WebpbMessage {

        public static final String WEBPB_METHOD = "";

        public static final String WEBPB_CONTEXT = "";

        public static final String WEBPB_PATH = "";

        public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

        @Override
        public WebpbMeta webpbMeta() {
            return WEBPB_META;
        }

        private String test;

        public Test17() {
        }

        public Test17(String test) {
            this.test = test;
        }
    }
}
