// Code generated by Webpb compiler, do not edit.
// https://github.com/linqu-tech/webpb
package test2;

import tech.linqu.webpb.runtime.WebpbMessage;
import tech.linqu.webpb.runtime.WebpbMeta;

public class Test implements WebpbMessage {

    public static final String WEBPB_METHOD = "";

    public static final String WEBPB_CONTEXT = "";

    public static final String WEBPB_PATH = "";

    public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

    @Override
    public WebpbMeta webpbMeta() {
        return WEBPB_META;
    }

    private Integer test1;

    private Boolean test2;

    private Boolean isTest3;

    public Test() {
    }

    public Test(Integer test1, Boolean test2, Boolean isTest3) {
        this.test1 = test1;
        this.test2 = test2;
        this.isTest3 = isTest3;
    }
}
