// Code generated by Webpb compiler, do not edit.
// https://github.com/linqu-tech/webpb
package test5;

public enum Test {

    DEFAULT(0), OTHER(100);

    private int value;

    Test(int value) {
        this.value = value;
    }

    public static Test fromValue(int value) {
        switch(value) {
            case 0:
                return DEFAULT;
            case 100:
                return OTHER;
            default:
                return null;
        }
    }

    public int getValue() {
        return this.value;
    }
}
