// Code generated by Webpb compiler, do not edit.
// https://github.com/linqu-tech/webpb
package test;

public enum Test5 {

    test1("text1"), test2("text2"), test3("2");

    private String value;

    Test5(String value) {
        this.value = value;
    }

    public static Test5 fromValue(String value) {
        switch(value) {
            case "text1":
                return test1;
            case "text2":
                return test2;
            case "2":
                return test3;
            default:
                return null;
        }
    }

    public String getValue() {
        return this.value;
    }
}
