// Code generated by Webpb compiler, do not edit.
// https://github.com/linqu-tech/webpb
package test;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import tech.linqu.webpb.runtime.WebpbMessage;
import tech.linqu.webpb.runtime.WebpbMeta;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
public class Test4 implements WebpbMessage {

    public static final String WEBPB_METHOD = "";

    public static final String WEBPB_CONTEXT = "";

    public static final String WEBPB_PATH = "";

    public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

    @Override
    public WebpbMeta webpbMeta() {
        return WEBPB_META;
    }

    private Long test1;

    private Integer test2;

    private String test3;

    public Test4() {
    }

    public Test4(Long test1, Integer test2, String test3) {
        this.test1 = test1;
        this.test2 = test2;
        this.test3 = test3;
    }
}
