// Code generated by Webpb compiler, do not edit.
// https://github.com/linqu-tech/webpb
package test;

public enum Test3 {

    test3_1("test3_1"), test3_2("test3_2"), test3_3("test3_3");

    private String value;

    Test3(String value) {
        this.value = value;
    }

    public static Test3 fromValue(String value) {
        switch(value) {
            case "test3_1":
                return test3_1;
            case "test3_2":
                return test3_2;
            case "test3_3":
                return test3_3;
            default:
                return null;
        }
    }

    public String getValue() {
        return this.value;
    }
}
