name: PR build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8,11,16]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: >
            runtime/processor/build/reports/jacoco/test/jacocoTestReport.csv
            runtime/java/build/reports/jacoco/test/jacocoTestReport.csv
            libs/commons/build/reports/jacoco/test/jacocoTestReport.csv
            libs/utilities/build/reports/jacoco/test/jacocoTestReport.csv
            sample/app/build/reports/jacoco/test/jacocoTestReport.csv
